apiVersion: v1
kind: Service-client
metadata:
  name: client-service
spec:
  selector:
    app: yolo-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000