version: '2'

services:
  client:
    container_name: client1_container
    image: eoloo/yolo-client:20.2.2
    ports:
    - 3000:3000
    networks:
      frontend-net:
        ipv4_address: 172.51.0.101   
  backend:
    container_name: backend1_container
    image: eoloo/yolo-backend:20.2.1
    ports: 
    - 5000:5000
    environment:
      PORT: 5000
      DATABASE_URL: 'mongodb+srv://EOLOO:Oloo1989@cluster0.ha1qbwy.mongodb.net/?retryWrites=true&w=majority'

    networks:
      backend-net:
        ipv4_address: 172.100.0.50
      frontend-net:
        ipv4_address: 172.51.0.51
    depends_on:
      - database

  database:
    container_name: back-end_database
    ports:
      - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    networks:
      backend-net:
        ipv4_address: 172.100.0.102
    volumes:
        - backend_volume:/data/db

networks:
  backend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
  frontend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.51.0.0/16
volumes:
  backend_volume: