apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo-backend
spec:
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: eoloo/yolo-backend:20.2.1
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: yolo-backend-config-map
                  key: NODE_ENV
            