version: '2'

services:
  client:
    container_name: client_container
    ports:
    - 10000:10000
    build:
      context: ../client
      dockerfile: Dockerfile
    networks:
      frontend-net:
        ipv4_address: 172.51.0.101    
  backend:
    container_name: back-end_container
    ports: 
    - 5000:5000
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      DATABASE_URL: 'mongodb+srv://EOLOO:Oloo1989@cluster0.ha1qbwy.mongodb.net/?retryWrites=true&w=majority'

    networks:
      backend-net:
        ipv4_address: 172.100.0.100
      frontend-net:
        ipv4_address: 172.51.0.100
    depends_on:
      - database

  database:
    container_name: backend_database
    ports:
      - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    networks:
      backend-net:
        ipv4_address: 172.100.0.101
    volumes:
        - backend_volume:/data/db

networks:
  backend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
  frontend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.51.0.0/16
volumes:
  backend_volume: