apiVersion: v1
kind: Service-backend
metadata:
  name: backend-service
spec:
  selector:
    app: yolo-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
apiVersion: v1
kind: Service-backend
metadata:
  name: backend-service
spec:
  selector:
    app: yolo-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
